# Generated by Django 3.1.4 on 2020-12-21 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='envia')),
            ],
        ),
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizar', models.DateTimeField(auto_now=True)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('primero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_arbol_primero', to=settings.AUTH_USER_MODEL)),
                ('segundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_arbol_segundo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
